export const VEHICLE_TYPE_ITEMS = [
  { label: "Sedan", value: "sedan" },
  { label: "SUV", value: "suv" },
  { label: "Truck", value: "truck" },
  { label: "Van", value: "van" },
  { label: "Hatchback", value: "hatchback" },
  { label: "Coupe", value: "coupe" },
  { label: "Convertible", value: "convertible" },
  { label: "Wagon", value: "wagon" },
  { label: "Crossover", value: "crossover" },
  { label: "Minivan", value: "minivan" },
  { label: "Pickup", value: "pickup" },
  { label: "Sports", value: "sports" },
  { label: "Luxury", value: "luxury" },
  { label: "Electric", value: "electric" },
  { label: "Hybrid", value: "hybrid" },
];

export const CA_PROVINCES = [
  "AB",
  "BC",
  "MB",
  "NB",
  "NL",
  "NS",
  "NT",
  "NU",
  "ON",
  "PE",
  "QC",
  "SK",
  "YT",
] as const;

export const ALL_BRANDS = [
  "Abarth",
  "Acura",
  "Aiways",
  "Alfa Romeo",
  "Alpine",
  "Aston Martin",
  "Audi",
  "BAIC",
  "Bentley",
  "BMW",
  "Bugatti",
  "Buick",
  "BYD",
  "Cadillac",
  "Changan",
  "Chery",
  "Chevrolet",
  "Chrysler",
  "Citroën",
  "Cupra",
  "Dacia",
  "Daewoo",
  "Daihatsu",
  "Datsun",
  "Dodge",
  "DS Automobiles",
  "Ferrari",
  "Fiat",
  "Ford",
  "GAC",
  "Genesis",
  "Geely",
  "GMC",
  "Great Wall",
  "Haval",
  "Holden",
  "Honda",
  "Hummer",
  "Hyundai",
  "Infiniti",
  "Isuzu",
  "Jaguar",
  "Jeep",
  "Kia",
  "Koenigsegg",
  "Lada",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Lotus",
  "Lucid",
  "Mahindra",
  "Maserati",
  "Maybach",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MG",
  "Mini",
  "Mitsubishi",
  "Nio",
  "Nissan",
  "Opel",
  "Pagani",
  "Peugeot",
  "Polestar",
  "Porsche",
  "Proton",
  "Ram",
  "Renault",
  "Rivian",
  "Rolls-Royce",
  "Saab",
  "Seat",
  "Skoda",
  "Smart",
  "SsangYong",
  "Subaru",
  "Suzuki",
  "Tata",
  "Tesla",
  "Toyota",
  "Vauxhall",
  "VinFast",
  "Volkswagen",
  "Volvo",
  "Wuling",
];

export type Transmission = "automatic" | "manual";

export type SelectOption = { label: string; value: string };

// Transmission choices
export const TRANSMISSIONS: Array<{ key: Transmission; label: string }> = [
  { key: "automatic", label: "Automatic" },
  { key: "manual", label: "Manual" },
];

// Brand list (same as your file)
export const POPULAR_BRANDS = [
  "Toyota",
  "Honda",
  "Ford",
  "Chevrolet",
  "Nissan",
  "Hyundai",
  "Kia",
  "Volkswagen",
  "BMW",
  "Mercedes-Benz",
  "Audi",
  "Tesla",
  "Lexus",
  "Mazda",
  "Subaru",
  "Jeep",
  "Ram",
  "GMC",
  "Volvo",
  "Porsche",
];

export type CAProvince = (typeof CA_PROVINCES)[number];

export type FuelType = "petrol" | "diesel" | "electric" | "hybrid";
export type BodyType = "sedan" | "suv" | "hatchback" | "mpv" | "pickup" | "van";

export const FUEL_TYPES: { key: FuelType; label: string }[] = [
  { key: "petrol", label: "Petrol" },
  { key: "diesel", label: "Diesel" },
  { key: "electric", label: "Electric" },
  { key: "hybrid", label: "Hybrid" },
];

export const BODY_TYPES: { key: BodyType; label: string }[] = [
  { key: "sedan", label: "Sedan" },
  { key: "suv", label: "SUV" },
  { key: "hatchback", label: "Hatchback" },
  { key: "mpv", label: "MPV" },
  { key: "pickup", label: "Pickup" },
  { key: "van", label: "Van" },
];

